server:
  port: 1991

spring:
  application:
    name: mm-member-service

  config:
    import: "optional:configserver:http://localhost:1881"

  datasource:
    url: jdbc:mysql://localhost:3306/liveshop
    username: liveshop
    password: "1234"

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false   # 개발환경: 마이그레이션 파일 수정 후 체크섬 불일치 무시


mybatis:
  type-aliases-package: co.kr.mmsoft.mmmemberservice.mybatis.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # db컬럼명 account_id ==> java 객체 accountId
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-minutes: 15
    refresh-token-minutes: 20160 #14일
  # 프론트엔드 URL (CORS 및 OAuth2 리다이렉트용)
  frontend-url: "http://localhost:5173"

my:
  logging:
    level: debug

logging:
  level:
    root: info

    #spring security 관련
    org.flywaydb: ${my.logging.level}
    org.springframework.security:  ${my.logging.level}
    org.springframework.security.web:  ${my.logging.level}
    org.springframework.security.authentication:  ${my.logging.level}
    org.springframework.security.authorization:  ${my.logging.level}

    # spring web 관련
    org.springframework.web: ${my.logging.level}
    org.springframework.web.servlet.DispatcherServlet: ${my.logging.level}

    co.kr.mmsoft.mmmemberservice: ${my.logging.level}

# mm-member-service의 설정 파일
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1761/eureka/